# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id$
Configuration parameters:
  url = https://translatewiki.net
  name = translatewiki

"""

from pywikibot import family
from pywikibot.tools import deprecated


class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'translatewiki'
        self.langs = {
            'en': 'translatewiki.net',
        }

    def scriptpath(self, code):
        return {
            'en': '/wiki',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'en': u'1.31.0-alpha',
        }[code]

    def protocol(self, code):
        return {
            'en': u'https',
        }[code]
